openapi: 3.0.3
info:
  title: API сервиса для тестового задания
  version: 0.1.0
tags:
  - name: cats
    description: Всё что касается котиков
  - name: users
    description: Всё что касается пользователей
paths:
  /likes:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - cats
      summary: Список лайков
      operationId: listLikes
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/LikeResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                statusCode: 401
                message: "Invalid token"
                error: "Unauthorized"
    post:
      security:
        - bearerAuth: []
      tags:
        - cats
      summary: Добавление лайка
      operationId: newLike
      requestBody:
        description: Новый лайк
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LikeRequest'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikeResponse'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                statusCode: 401
                message: "Invalid token"
                error: "Unauthorized"
        '404':
          description: Cat not found in TheCatAPI
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                statusCode: 404
                message: "cat_id not found in TheCatAPI"
                error: "Not Found"
        '409':
          description: Like already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                statusCode: 409
                message: Like already exists
                error: Conflict
  /likes/{cat_id}:
    delete:
      security:
        - bearerAuth: [ ]
      tags:
        - cats
      summary: Удаление лайка
      operationId: dropLike
      parameters:
        - name: cat_id
          description: id котика из https://thecatapi.com
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                statusCode: 401
                message: "Invalid token"
                error: "Unauthorized"
        '404':
          description: Like not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                statusCode: 404
                message: "Like not found"
                error: "Not Found"
  /user:
    post:
      tags:
        - users
      summary: Добавление пользователя
      operationId: newUser
      requestBody:
        description: Новый пользователь
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '201':
          description: Successful operation
          headers:
            X-Auth-Token:
              description: Токен для последующей авторизации, например sha256(user_id + secret_salt)
              example: 3525dcdddea774939652f7f11df6d7db10a9db35a5d758c64d600a00c1cc41be
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                statusCode: 409
                message: User with this login already exists
                error: Conflict

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Ожидается токен, выдаваемый при регистрации пользователя
      bearerFormat: SHA256
  schemas:
    User:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          description: Логин пользователя
        password:
          type: string
          description: Пароль пользователя
    LikeRequest:
      type: object
      required:
        - cat_id
        - cat_url
      properties:
        cat_id:
          description: Идентификатор котика из https://thecatapi.com
          type: string
          example: asu7as
        cat_url:
          description: URL картинки котика
          format: uri
          type: string
          example: https://cdn2.thecatapi.com/images/asu7as.jpg
    LikeResponse:
      type: object
      required:
        - cat_id
        - cat_url
        - created_at
      properties:
        cat_id:
          description: Идентификатор котика из https://thecatapi.com
          type: string
          example: asu7as
        cat_url:
          description: URL картинки котика
          format: uri
          type: string
          example: https://cdn2.thecatapi.com/images/asu7as.jpg
        created_at:
          type: string
          format: date-time
          example: 2024-03-20T09:12:28Z
          description: Время создания лайка
    ErrorResponse:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
          example: 400
        message:
          oneOf:
            - type: array
              items:
                type: string
              example: 
                - "property extra should not exist"
                - "login should not be empty"
                - "password must be a string"
            - type: string
              example: "User with this login already exists"
        error:
          type: string
          example: Bad Request
